name: BuyPermissions
version: ${project.version}
main: me.glaremasters.buypermissions.BuyPermissions
softdepend: [Vault]
authors: [blockslayer22]
description: BuyPermissions

commands:
  bp:
    description: Default help info